<a href="https://colab.research.google.com/github/niteshkamboj2811/Python_Practice/blob/main/Magnimind_Python_Mini_Bootcamp_Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
grocery_list = ['tomatoes', 'bread', 'cheese']

for i in grocery_list:
  print(i)

tomatoes
bread
cheese


In [ ]:
num = int(input('Enter the number: '))

if num < 10:
  print(f'{num} is less than 10')
elif num > 10:
  print(f'%d is more than 10' % num)
elif num > 15:
  print('{0} is more than 15'.format(num))

Enter the number: 16
16 is more than 10


In [ ]:
def shave_dog(dog_name, dog_weight):

  new_weight = dog_weight * .95

  print(f"just shaver {dog_name} and not the weight is : {new_weight}")
  print('just shaved {} and weight is {}'.format(dog_name, dog_weight))

In [ ]:
shave_dog('kaju', 100)

just shaver kaju and not the weight is : 95.0
just shaved kaju and weight is 100


In [ ]:
print('{} + {}'.format('a', 1))

a + 1


In [ ]:
def add_two(num):
  return num + 2

def add_five(num):
  return num + 5

In [ ]:
add_five(add_two(9))

16

In [ ]:
try:
  print('I like this' / 4)
except Exception as e:
  print('your error: ', e)

print('\nFinished')

your error:  unsupported operand type(s) for /: 'str' and 'int'

Finished


In [ ]:
x = 'hello'

if x != 'goodbye':
  raise TypeError(f'"{x}" is not goodbye')

TypeError: ignored

In [ ]:
list1 = []

for i in range(20):
  if i > 2:
    list1.append(i)

print(list1)

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [ ]:
list1 = [x for x in range(20) if x > 2]

print(list1)

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [ ]:
list1 = list(map(lambda x: x, range(20)))

In [ ]:
print(list1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [ ]:
output = lambda x: x * 5

In [ ]:
output(4)

20

In [ ]:
list1 = list(filter(lambda x: x > 2, range(20)))

In [ ]:
print(list1)

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [ ]:
list1 = list(map(lambda x: x>2, range(20)))

list1

[False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [ ]:
list1 = list(map(lambda x: x*2, range(20)))

list1

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]

In [ ]:
longer_list_of_lists = [[1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 8, 7, 6],
                        [5, 4, 3, 2]]

In [ ]:
import numpy as np

np.sum(longer_list_of_lists)

80

In [ ]:
list_to_array = np.array(longer_list_of_lists)

In [ ]:
list_to_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6],
       [5, 4, 3, 2]])

In [ ]:
np.array([1, 3, 4])

array([1, 3, 4])

In [ ]:
print(np.array([1, 2, 3, 4], dtype=float))

[1. 2. 3. 4.]


###Cont


In [ ]:
x = -5
np.abs(x)

5

In [ ]:
print(np.floor(3.5))
print('\n')
print(np.ceil(3.5))

3.0


4.0


In [ ]:
data1 = np.array([1, 2, 3, 4, 5])
# np.max(data1)
# np.min(data1)
# np.std(data1)
np.var(data1)

2.0

In [ ]:
!gdown https://drive.google.com/uc?id=1QGV_zFOefmTWIJQqJmDS9LRpgUfnhZ2Y

Downloading...
From: https://drive.google.com/uc?id=1QGV_zFOefmTWIJQqJmDS9LRpgUfnhZ2Y
To: /content/Cats.csv
100% 274/274 [00:00<00:00, 645kB/s]


In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Cats.csv')

In [ ]:
df.head()

Name   Color     Fur  Weight   Owner  Age
0  Ridley   Black  Fluffy       4   Tyler    3
1    Mish  Tuxedo   Short       3   Ariel    4
2     Moe   Black  Fluffy       5  Dustin    4
3    Kaya    Grey   Short       4  Gordon    8
4  Shadow   Black   Short       3   Nicky   10

In [ ]:
df.shape

(8, 6)

In [ ]:
df2 = df.drop(['Owner'], axis=1)

In [ ]:
df2

Name   Color     Fur  Weight  Age
0    Ridley   Black  Fluffy       4    3
1      Mish  Tuxedo   Short       3    4
2       Moe   Black  Fluffy       5    4
3      Kaya    Grey   Short       4    8
4    Shadow   Black   Short       3   10
5      Otis    Grey  Fluffy       4    6
6     Elvis   Brown  Fluffy       8   16
7  Kaboodle   Black  Fluffy       5   15

In [ ]:
df.iloc[[0]]

Name  Color     Fur  Weight  Owner  Age
0  Ridley  Black  Fluffy       4  Tyler    3

In [ ]:
df.loc[[4]]

Name  Color    Fur  Weight  Owner  Age
4  Shadow  Black  Short       3  Nicky   10

In [ ]:
df2['Fur'][3]

'Short'

In [ ]:
df2['vet_visit'] = [x for x in range(8)]

In [ ]:
df2

Name   Color     Fur  Weight  Age  vet_visit
0    Ridley   Black  Fluffy       4    3          0
1      Mish  Tuxedo   Short       3    4          1
2       Moe   Black  Fluffy       5    4          2
3      Kaya    Grey   Short       4    8          3
4    Shadow   Black   Short       3   10          4
5      Otis    Grey  Fluffy       4    6          5
6     Elvis   Brown  Fluffy       8   16          6
7  Kaboodle   Black  Fluffy       5   15          7

In [ ]:
df2['vet_visit'][2] = 5

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
df2['vet_visit'] = df2['vet_visit']*2

In [ ]:
df2

Name   Color     Fur  Weight  Age  vet_visit
0    Ridley   Black  Fluffy       4    3          0
1      Mish  Tuxedo   Short       3    4          2
2       Moe   Black  Fluffy       5    4         10
3      Kaya    Grey   Short       4    8          6
4    Shadow   Black   Short       3   10          8
5      Otis    Grey  Fluffy       4    6         10
6     Elvis   Brown  Fluffy       8   16         12
7  Kaboodle   Black  Fluffy       5   15         14

In [ ]:
df2 = df2.sort_values('Age')

In [ ]:
df2

Name   Color     Fur  Weight  Age  vet_visit
0    Ridley   Black  Fluffy       4    3          0
1      Mish  Tuxedo   Short       3    4          2
2       Moe   Black  Fluffy       5    4         10
5      Otis    Grey  Fluffy       4    6         10
3      Kaya    Grey   Short       4    8          6
4    Shadow   Black   Short       3   10          8
7  Kaboodle   Black  Fluffy       5   15         14
6     Elvis   Brown  Fluffy       8   16         12

In [ ]:
df2['Owner'] = df['Owner']

In [ ]:
df2

Name   Color     Fur  Weight  Age  vet_visit   Owner
0    Ridley   Black  Fluffy       4    3          0   Tyler
1      Mish  Tuxedo   Short       3    4          2   Ariel
2       Moe   Black  Fluffy       5    4         10  Dustin
5      Otis    Grey  Fluffy       4    6         10   Nicky
3      Kaya    Grey   Short       4    8          6  Gordon
4    Shadow   Black   Short       3   10          8   Nicky
7  Kaboodle   Black  Fluffy       5   15         14    Cory
6     Elvis   Brown  Fluffy       8   16         12     Tom

In [ ]:
df2['Owner'][3] = np.nan

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
df2

Name   Color     Fur  Weight  Age  vet_visit   Owner
0    Ridley   Black  Fluffy       4    3          0   Tyler
1      Mish  Tuxedo   Short       3    4          2   Ariel
2       Moe   Black  Fluffy       5    4         10  Dustin
5      Otis    Grey  Fluffy       4    6         10   Nicky
3      Kaya    Grey   Short       4    8          6     NaN
4    Shadow   Black   Short       3   10          8   Nicky
7  Kaboodle   Black  Fluffy       5   15         14    Cory
6     Elvis   Brown  Fluffy       8   16         12     Tom

In [ ]:
df2.dropna()

Name   Color     Fur  Weight  Age  vet_visit   Owner
0    Ridley   Black  Fluffy       4    3          0   Tyler
1      Mish  Tuxedo   Short       3    4          2   Ariel
2       Moe   Black  Fluffy       5    4         10  Dustin
5      Otis    Grey  Fluffy       4    6         10   Nicky
4    Shadow   Black   Short       3   10          8   Nicky
7  Kaboodle   Black  Fluffy       5   15         14    Cory
6     Elvis   Brown  Fluffy       8   16         12     Tom

In [ ]:
sum(df2['vet_visit'])

62

In [ ]:
list1 = [1, 3, 4, 6, 3, 4, 7]

sorted(list1)

[1, 3, 3, 4, 4, 6, 7]

In [ ]:
print(np.sort(list1)) == sorted(list1)

[1 3 3 4 4 6 7]


False

In [ ]:
for i in np.sort(list1):
  print(i)

1
3
3
4
4
6
7


In [ ]:
for i in sorted(list1):
  print(i)

1
3
3
4
4
6
7


In [ ]:
print(np.sort(list1)) == sorted(list1)

[1 3 3 4 4 6 7]


False

In [ ]:
len(np.sort(list1))

7

In [ ]:
#I would love to know more about industry application of GPT-3. I though it came like a game changer for AI real world application like generating SQL queries and went away. It’s really interesting. 

In [ ]:
number = 123

